### ISSUE TITLE
Drag-and-drop and zooming content to pdf is supported？By the way, when will vue3 be supported

### ISSUE THREAD

**Issue by baixjian** [CoderMonkie/vue-grabbing-box#26]

**Comment by CoderMonkie** [comment]
> Drag-and-drop and zooming content to pdf is supported

I havnt try that, it may support if you use a pdf preview tool component to show pdf, I suppose.

> By the way, when will vue3 be supported

If there is a need, I will try my best to arrange time to do it

**Comment by CoderMonkie** [comment]
Now vue3 is supported~
